addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.17.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.5.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.13.0")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"               % "5.10.0")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"           % "1.9.2")
